CREATE TABLE IF NOT EXISTS user (
  username VARCHAR(20)  NOT NULL,
  password VARCHAR(255) NOT NULL,
  email    VARCHAR(89)  NOT NULL,

  PRIMARY KEY (username)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;